### 대출 신청 등록
POST http://localhost:8080/applications
Content-Type: application/json

< ./json/CreateApplication.json

### 대출 신청 내역 조회
GET http://localhost:8080/applications/1
Content-Type: application/json

### 대출 신청 내역 수정
PUT http://localhost:8080/applications/1
Content-Type: application/json

< ./json/UpdateApplication.json

### 대출 신청 내역 삭제
DELETE http://localhost:8080/applications/1
Content-Type: application/json

### 대출 신청시 사용자가 동의한 약관 id 정보를 전달
POST http://localhost:8080/applications/1/terms
Content-Type: application/json

< ./json/CreateAcceptTerms.json


### 단일 파일 업로드
POST http://localhost:8080/applications/1/files
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test1.txt"

< ./requestFIle/test1.txt
--boundary--

### 단일 파일 다운로드
GET http://localhost:8080/applications/1/files?fileName=test1.txt
Content-Type: application/octet-stream

### 업로드된 전체 파일 리스트 조회
GET http://localhost:8080/applications/1/files/infos
Content-Type: application/json


### 업로드된 전체 파일 삭제
DELETE http://localhost:8080/applications/1/files
Content-Type: application/json
