### 대출 신청 등록
POST http://localhost:8080/applications
Content-Type: application/json

< ./json/CreateApplication.json

### 대출 신청 내역 조회
GET http://localhost:8080/applications/1
Content-Type: application/json

### 상담 내역 수정
PUT http://localhost:8080/applications/1
Content-Type: application/json

< ./json/UpdateApplication.json

### 상담 내역 삭제
DELETE http://localhost:8080/applications/1
Content-Type: application/json